### ISSUE TITLE
Option to pad user name with '0' in create tenants

### ISSUE THREAD

**Issue by satyaj** [gpe-mw-ansible-org/3scale_multitenant#4]
For using the create tenants action on 3scale provisioned with Integreatly, the 3scale tenant domains should be : evals01-3scale-admin.$OCP_DOMAIN. The users 1 - 9 have a '0' padding in front . e.g evals01, evals02 ... evals09. Other users evals10 - evals50 do not need this padding.

hence, please provide this as an option in the script.

**Comment by jbride** [comment]
Tenant names are now padded by default.
