### ISSUE TITLE
Option to provide OCP_AMP_NAMESPACE instead of OCP_AMP_ADMIN_ID

### ISSUE THREAD

**Issue by satyaj** [gpe-mw-ansible-org/3scale_multitenant#5]
For 3scale multitenant env provisioned with Integreatly, the namespace is '3scale'. It does not follow the 3scale-mt-$OCP_AMP_ADMIN_ID convention. Hence, please provide an option to provide this parameter for create tenants.

**Comment by jbride** [comment]
Standardized on the variable called:  API_MANAGER_NS     (which is also the same env variable we use throughout our 3scale API Mgmt courses).

Default value of API_MANAGER_NS=3scale-mt-$OCP_AMP_ADMIN_ID

However, API_MANAGER_NS can now be over-written when provisioning the API Manager, provisioning the tenants and deleting the API Manager.
